@startuml webserver_structure

skinparam BackgroundColor White
skinparam componentStyle rectangle

component HTTPServer {
	[Config] #Gray
	[ConfigParser] #LightGray
		component Connection <<>> {
			() buffer #Gray
				   [HTTPRequestMessage] #Gray
				   [HTTPResponseMessage] #Gray
	   		component HTTPRequestHandler <<>>{
				   [validator,analyzer] #Azure
			}
			component HTTPRequestHandlerFactory <<>> {
				   [RequestParser] #LightGray
				   [RequestReader]#LightGray

			}
		}
		component "kqueue_loop" {
			[new event] #Linen
		}
		[ConnectionFactory?] #White
}

() config_file #Gray
[Client] #Linen


[Client] ..> [new event] #Black : HTTPRequest
[Config] --> [new event]
[ConnectionFactory?] --> Connection <<>> : create
[new event] ..> [buffer] #Black : data
() config_file --> [ConfigParser] #Black
[ConfigParser] --> [Config] #Black
[Config] --> [validator,analyzer] #Black
' [Config] --> [new event] : port, ip address
[HTTPRequestMessage] --> HTTPRequestHandler <<>>
' [HTTPResponseMessage] --> HTTPRequestHandler <<>>
[buffer] ..> [RequestReader] #Black
[RequestReader] --> [RequestParser] #Black
[RequestReader] --> [HTTPResponseMessage] #Black : if error
[RequestParser] --> [HTTPRequestMessage] #Black
[RequestParser] --> [HTTPResponseMessage] #Black : if error 
[validator,analyzer] --> [HTTPResponseMessage] #Black
[HTTPResponseMessage] ..> [Client] #Black : HTTPResponse
' HTTPRequestHandlerFactory <<>> --> HTTPRequestHandler <<>> : create


@enduml