@startuml webserver_structure

skinparam BackgroundColor White
skinparam componentStyle rectangle

component Server {
	[Config] #Gray
	[ConfigParser] #LightGray
		component Connection <<>> {
			() buffer #Gray
	   		component RequestHandler <<>>{
				   [HTTPRequestMessage] #Gray
				   [HTTPResponseMessage] #Gray
				   [RequestParser] #LightGray
				   [ResponseHandler] #LightGray
			}
		}
		package "kernel queue" {
			[new event] #Linen
		}
}

() config_file #Gray
[Client] #LightGreen


[Client] ..> [new event] #Black : HTTPRequest
[HTTPResponseMessage] ..> [new event]  #Black : HTTPResponse
 [new event] ..> [Client] #Black : HTTPResponse
' [Config] --> [new event]
[new event] ..> [buffer] #Black : data
() config_file --> [ConfigParser] #Black
[ConfigParser] --> [Config] #Black
[Config] --> [ResponseHandler] #Black
[buffer] ..> [RequestParser] #Black
[RequestParser] --> [HTTPRequestMessage] #Black
[HTTPRequestMessage] --> [ResponseHandler] #Black
[ResponseHandler] --> [HTTPResponseMessage] #Black



@enduml