@startuml webserver_structure

skinparam BackgroundColor White
skinparam componentStyle rectangle

component Server {
	[Config] #Gray
	[ConfigParser] #LightGray
		component Connection <<>> {
			() buffer #Gray
	   		component RequestHandler <<>>{
				   [HTTPRequestMessage] #Gray
				   [HTTPResponseMessage] #Gray
				   [RequestParser] #LightGray
				   [validator,analyzer] #Azure
			}
		}
		component "kqueue_loop" {
			[new event] #Linen
		}
}

() config_file #Gray
[Client] #Linen


[Client] ..> [new event] #Black : HTTPRequest
[Config] --> [new event]
[new event] ..> [buffer] #Black : data
() config_file --> [ConfigParser] #Black
[ConfigParser] --> [Config] #Black
[Config] --> [validator,analyzer] #Black
[buffer] ..> [RequestParser] #Black
[RequestParser] --> [HTTPRequestMessage] #Black
[HTTPRequestMessage] --> [validator,analyzer] #Black
[validator,analyzer] --> [HTTPResponseMessage] #Black
[HTTPResponseMessage] ..> [Client] #Black : HTTPResponse
' HTTPRequestHandlerFactory <<>> --> HTTPRequestHandler <<>> : create


@enduml